### PR TITLE
Move last register_* methods to extension_points

### PR DESCRIPTION
**Pull request by zas**
# Summary

* This is a…
  * [ ] Bug fix
  * [ ] Feature addition
  * [x] Refactoring
  * [ ] Minor / simple change (like a typo)
  * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): PICARD-XXX

# Solution

# Action

Additional actions required:
* [ ] Update Picard [documentation](https://github.com/metabrainz/picard-docs) (please include a reference to this PR)
* [ ] Other (please specify below)

### CODE REVIEW

**Comment by zas** [comment]
@phw: should we regroup those in one file? If yes, under which name?

**Comment by phw** [comment]
> should we regroup those in one file? If yes, under which name?

Yes, I think those could be grouped. The docs call them "event hooks", so maybe `event_hooks` ?

https://picard-docs.musicbrainz.org/en/appendices/plugins_api.html#event-hooks

**Review by phw — DISMISSED** [review]
This looks good to go. Only thing to change might be the common file for the extension points, depending on what we decide there.

**Review by phw — APPROVED** [review]
LGTM

**Pull request merged**
