### PR TITLE
Ensure rating submission XML is valid

### PR DESCRIPTION
**Pull request by phw**
# Summary

* This is a…
  * [x] Bug fix
  * [ ] Feature addition
  * [ ] Refactoring
  * [ ] Minor / simple change (like a typo)
  * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

MBAPIHelper._xml_ratings does not handle encoding the input parameters.

# Solution
Properly XML encode provided data for rating submission. Also ensure rating is an integer as expected.

In the current implementation both should already be guaranteed. `track.id`  is always a MBID as given by MB service, and the rating widget's `self._rating`  is always an integer. But for a complete implementation in the context of `MBAPIHelper`  and to avoid potential issues both should be handled.

# Action

### CODE REVIEW

**Review by zas — APPROVED** [review]
Good move.

**Comment by phw** [comment]
@zas Do you think we should do anything about https://github.com/metabrainz/picard/pull/2019/checks?check_run_id=4652255922 ? I actually think we can just ignore it, using quoteattr to replace the common entities should really be enough for our use case of building this string I guess. If someone wants to attack the MB server with a bad XML they don't need to use Picard for that really.

**Comment by zas** [comment]
> @zas Do you think we should do anything about https://github.com/metabrainz/picard/pull/2019/checks?check_run_id=4652255922 ? I actually think we can just ignore it, using quoteattr to replace the common entities should really be enough for our use case of building this string I guess. If someone wants to attack the MB server with a bad XML they don't need to use Picard for that really.

I agree we can just ignore it, but we need to silent the warning explicitly to make Codacy happy.

**Comment by phw** [comment]
> but we need to silent the warning explicitly to make Codacy happy.

Did that in 1370fc5064b28dd3818e2f27778f166895a06a47

**Review by zas — APPROVED** [review]

**Pull request merged**
