### PR TITLE
Add installer italian language

### PR DESCRIPTION
**Pull request by bovirus**

### CODE REVIEW

**Comment by phw** [comment]
Thank you very much, this looks good. Could you uncomment the line to load Italian language in https://github.com/metabrainz/picard/blob/master/installer/picard-setup.nsi.in#L96 ? Then we will get actual test builds as part of this pull request.

**Comment by bovirus** [comment]
Done!

**Comment by phw** [comment]
Oh, sorry, I meant to just add this commit to this pull request, not a separate one. If it is in two separate pull requests we can't test the changes before merge.

**Comment by phw** [comment]
I combined your two commits into a separate PR at https://github.com/metabrainz/picard/pull/1156 . Thanks a lot for this, once we have a successful test build I will merge it.

**Pull request closed without merging**
