### PR TITLE
Filedialog wrappers

### PR DESCRIPTION
**Pull request by zas**
# Summary

* This is a…
  * [ ] Bug fix
  * [ ] Feature addition
  * [x] Refactoring
  * [ ] Minor / simple change (like a typo)
  * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): PICARD-XXX

# Solution

# Action

Additional actions required:
* [ ] Update Picard [documentation](https://github.com/metabrainz/picard-docs) (please include a reference to this PR)
* [ ] Other (please specify below)

### CODE REVIEW

**Comment by zas** [comment]
For reference https://github.com/metabrainz/picard/pull/2502#discussion_r1618311678

**Comment by phw** [comment]
Copying my comment from #2502:

Just something we need to be aware of with this implementation: `FileDialog.getSaveFileName` gives the caller a `QFileDialog`, not a `FileDialog`.

This might become unexpected should we for example replace existing uses of `QFileDialog` with `FileDialog` and add additional default handling to this class.

We currently have one direct instantiation of `QFileDialog` at https://github.com/metabrainz/picard/blob/master/picard/tagger.py#L1204 . Probably this should also be changed to the static helper functions instead?

I think I avoided the helper functions when implementing this because I found the many arguments to a single static function harder to use then just instantiating the class itself and setting properties on it.

Another thing is especially with these functions with many parameters but only using `**kwargs` that I need to lookup the possible parameters and code completion cannot assist me. Currently I would get something like this:

grafik

That would definitely motivate me to avoid the wrapper and use the class directly. Maybe we should just have our very own specific wrappers that open the dialog as we actually need it right now so we can easily use it and have consistent behavior.

Another point is how we dealt with the separate `MultiDirsSelectDialog`. Should we make this a subclass of `FileDialog`? We should also use consistent caption there at least.

**Comment by zas** [comment]
> Just something we need to be aware of with this implementation: `FileDialog.getSaveFileName` gives the caller a `QFileDialog`, not a `FileDialog`.

I'm not sure to understand, what do you mean by "gives the caller a `QFileDialog`, not a `FileDialog`." ?



> We currently have one direct instantiation of `QFileDialog` at https://github.com/metabrainz/picard/blob/master/picard/tagger.py#L1204 . Probably this should also be changed to the static helper functions instead?

https://github.com/metabrainz/picard/pull/2503/files#diff-754164b29034aa27e27d501630b16fe491c78108500b10caeab6b272bc240fbdR1205 changes it to use `FileDialog`, the only difference here is that `file_chooser` becomes a `FileDialog`, but that's still an instance of `QFileDialog`.
Again, not sure to understand what's the problem here.



> Another thing is especially with these functions with many parameters but only using `**kwargs` that I need to lookup the possible parameters and code completion cannot assist me.

We could define arguments in static methods instead (in fact, that what I did first), but I went this way because I had issue with `options` default. It doesn't seem `QFileDialog.Options()` works (pyqt?), so I used `QFileDialog.Option(0)`, which provides an empty enum flag as default for options parameter.



> Another point is how we dealt with the separate `MultiDirsSelectDialog`. Should we make this a subclass of `FileDialog`? We should also use consistent caption there at least.

Or just a new static method of `FileDialog`.

**Comment by zas** [comment]
> Or just a new static method of `FileDialog`.

I did that in https://github.com/metabrainz/picard/pull/2503/commits/13dfe589b96784c3321614cbe2b0ab6e913a9810

**Comment by zas** [comment]
> 
> We could define arguments in static methods instead

See https://github.com/metabrainz/picard/pull/2503/commits/672c37eef62d0416bf424000e8a47658cd8ad187

**Review by phw — APPROVED** [review]

**Pull request merged**
