### PR TITLE
PICARD-896: Replace "Submit" icon with AcoustID one.

### PR DESCRIPTION
**Pull request by Freso**
Replaces the "picard-submit" icon with the icon used by the acoustid-fingerprinter project. The "picard-submit" icon resembles the old MusicBrainz brain logo, but the submit button doesn't actually submit anything to MusicBrainz since the switch from using PUIDs to using AcoustID, but instead submits to the AcoustID.org server. A lot of people are already confused by this, so making it visually a bit less connected to MusicBrainz might help this confusion, however slightly.

`acoustid-fingerprinter.svg` was copied directly from https://bitbucket.org/acoustid/acoustid-fingerprinter/src/632e87969c3a5562a5d4842b03613267ba6236b2/images/ and then converted to a 22×22 PNG using Inkscape and run through `optipng` and `advpng` as per commit d26c908587a3782589066f1d9c7040187a99419f.

The acoustid-fingerprinter icon was made by Lukáš Lalinský and is available under the GPL2 license, the same as MusicBrainz Picard: https://bitbucket.org/acoustid/acoustid-fingerprinter/src/632e87969c3a5562a5d4842b03613267ba6236b2/COPYING.txt

Jira ticket: https://tickets.metabrainz.org/browse/PICARD-896

### CODE REVIEW

**Comment by Freso** [comment]
Should I add a note to AUTHORS, or is the Git commit message attribution enough?

**Comment by zas** [comment]
> Should I add a note to AUTHORS, or is the Git commit message attribution enough?

I think we should autogenerate AUTHORS from Git ... i is a pain to maintain such file.
But for now ... well, do whatever you think is the best ;)

**Comment by zas** [comment]
@Freso : can you fix conflicts please ?

**Comment by Freso** [comment]
@lalinsky Is the git commit message enough attribution, or would it be better to denote it in the AUTHORS file (where we have attribution for other image files as well)?

**Pull request merged**
