### PR TITLE
Tidy up mbjson (pass 3)

### PR DESCRIPTION
**Pull request by zas**
# Summary

* This is a…
  * [ ] Bug fix
  * [ ] Feature addition
  * [x] Refactoring
  * [ ] Minor / simple change (like a typo)
  * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): PICARD-XXX

# Solution

# Action

### CODE REVIEW

**Review by rdswift — APPROVED** [review]
Looks good to me.  Thanks.

**Review by phw — DISMISSED** [review]

**Comment by zas** [comment]
I'm done for this pass, 96% coverage, only 15 lines not covered now.

**Review by rdswift — APPROVED** [review]
Looks good.  Nice work.  Thanks.

**Review by phw — APPROVED** [review]
Looks good. Great to have extended tests

**Pull request merged**
