### PR TITLE
PICARD-408: Options pane is obscured

### PR DESCRIPTION
**Pull request by suhas2go**
I know that another [PR](https://github.com/metabrainz/picard/pull/491) already exists for this [issue](https://tickets.metabrainz.org/browse/PICARD-408), I just wanted to put forward this approach. Rather than simply increasing the default options dialog size, I have set the minimum width according to the contents of the pages_tree. 
This allows the splitter to nicely snap at the perfect pane size.
reszied_pane
Note that I have expanded all the items to show that it fits, they're not expanded by default.

### CODE REVIEW

**Comment by zas** [comment]
Imho a much better approach than https://github.com/metabrainz/picard/pull/491 :+1:

**Comment by suhas2go** [comment]
@zas At the default size, resizing is not possible. On increasing the size of the options dialog the pane also grows, the splitter allows to reduce the size of the option pane up to the minimum.

**Comment by zas** [comment]
> @zas At the default size, resizing is not possible. On increasing the size of the options dialog the pane also grows, the splitter allows to reduce the size of the option pane up to the minimum.

Yup, i still have problems with Options dialog:
- i can't reduce size
- i can increase the size, but the pane on the left can only be downized to nothing or default, and increased a bit or to max dialog width, no smooth resize
- the behavior is somehow unpredicable :(

That said this stuff is plagued with such issues since years, not sure the actual problem is in this PR.

**Comment by suhas2go** [comment]
@zas I'll work on the issue of resizing in the Options Dialog when I get time. Is there a corresponding ticket?

**Comment by zas** [comment]
> @zas I'll work on the issue of resizing in the Options Dialog when I get time. Is there a corresponding ticket?
https://tickets.metabrainz.org/browse/PICARD-930

**Pull request merged**
