### PR TITLE
PICARD-143, PICARD-1510: Add hooks for file addition to and file removal from a track

### PR DESCRIPTION
**Pull request by Harakku**
* register_file_post_addition_to_track_processor() and register_file_post_removal_from_track_processor()

# Summary

* This is a…
    * [ ] Bug fix
    * [x] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:
Adds a file-added-to-track hook and a file-removed-from-track hook.

# Problem

* JIRA ticket (_optional_): [PICARD-143](https://tickets.metabrainz.org/browse/PICARD-143), [PICARD-1510](https://tickets.metabrainz.org/browse/PICARD-1510)

# Solution

# Action
Plugin API version needs an update I think.

### CODE REVIEW

**Comment by zas** [comment]
LGTM, but can you create matching ticket and prefix the PR's title with PICARD-XXXX ?
It helps to have informative Changelog.

**Comment by Harakku** [comment]
I kinda just realized that register_file_post_addition_to_track_processor (etc.) would probably make more sense since the hooks care about tracks, not albums. The hooks do trigger when moving a file from one track to another inside one album (since I guess moving a track is just removing it and adding it to another track.). Hmm.

**Comment by zas** [comment]
@Harakku can you fix conflicts so i can merge this PR ?

**Comment by zas** [comment]
@Harakku just a minor thing to fix before we can merge: https://app.codacy.com/app/MetaBrainz/picard/pullRequest?prid=3551146

**Pull request merged**
