### PR TITLE
Use python3 super function instead of calling by class name

### PR DESCRIPTION
**Pull request by vishichoudhary**
# Summary

* This is a…
    * [ ] Bug fix
    * [ ] Feature addition
    * [x] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem
While understanding the picard codebase i am encountering various python2 oriented code. This pr will port them to python3.

### CODE REVIEW

**Comment by zas** [comment]
@vishichoudhary : what's the status of this ?

**Comment by vishichoudhary** [comment]
@zas i dont know what to do with this pr. As the codebase is big and i can't really look each module. I think we should merge it . But what should we do if i found more ?

**Comment by samj1912** [comment]
@vishichoudhary I think it is very much possible to port individual python 2 patterns to python3 if you do them systematically. Otherwise Picard 2.0 wouldn't be py3 ;).

So that leaves that out as an excuse to merge this PR. I really am not in the favor the the process you described - you finding things and making a commit with 1-2 lines of similar changes. It pollutes the git history.

**Comment by vishichoudhary** [comment]
@samj1912 give me just 3 - 4 days  i will look in each file.

**Comment by samj1912** [comment]
@vishichoudhary  a better way would be to list out all the possible python2 remnants you can find and change them across all the modules (possibly use a code refactoring tool or IDE for this)

**Comment by vishichoudhary** [comment]
@sambhav @zas  . I think it's complete now.

**Pull request merged**
