### PR TITLE
PICARD-973: process events before exiting

### PR DESCRIPTION
**Pull request by Sophist-UK**
Resolves [PICARD-973](https://tickets.metabrainz.org/browse/PICARD-973).

### CODE REVIEW

**Comment by Sophist-UK** [comment]
Away for 2 weeks with email and web but no dev environment - other's can address review comments etc. or they can wait until I am back.

**Comment by mineo** [comment]
This also includes the changes from #609

**Comment by Sophist-UK** [comment]
Sorry.  I can look at rebasing this without #609 once I am back in the UK in a couple of weeks.

**Comment by zas** [comment]
> Sorry. I can look at rebasing this without #609 once I am back in the UK in a couple of weeks.

No need to rebase, merge will cop with already existing commits (there are identical to those in #609)

**Pull request merged**
