### PR TITLE
Improve records name & path in log output

### PR DESCRIPTION
**Pull request by zas**
# Summary

* This is a…
  * [ ] Bug fix
  * [ ] Feature addition
  * [x] Refactoring
  * [ ] Minor / simple change (like a typo)
  * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

Depending on the way Picard is executed, paths in log can be long without giving much infos.

Before:

```
D: 09:14:09,382 /home/zas/src/picard/picard/webservice/ratecontrol.decrement_requests:146: ('ia601602.us.archive.org', 80): Decrementing requests to: 0
D: 09:14:09,383 /home/zas/src/picard/picard/webservice/__init__._handle_reply:523: Received reply for http://ia601602.us.archive.org/14/items/mbid-0bb956a7-da2e-4083-861a-0dbd5e839cdf/mbid-0bb956a7-da2e-4083-861a-0dbd5e839cdf-35878421569_thumb1200.jpg: HTTP 200 (OK)  (CACHED)
D: 09:14:09,384 /home/zas/src/picard/picard/coverart/image.__init__:91: Saving image data 11463660cbc8ad7ac28c974a51e9e086 to '/tmp/picardxpe_9zn7.jpg'
D: 09:14:09,384 /home/zas/src/picard/picard/coverart/__init__._set_metadata:73: Cover art image stored to metadata: CaaCoverArtImage(url='http://coverartarchive.org/release/0bb956a7-da2e-4083-861a-0dbd5e839cdf/35878421569-1200.jpg', types=['front', 'spine'], support_types=True, support_multi_types=True, is_front=False) [w=1200 h=936 mime=image/jpeg ext=.jpg datalen=281208 file=/tmp/picardxpe_9zn7.jpg]
D: 09:14:09,384 /home/zas/src/picard/picard/coverart/__init__.next_in_queue:148: Skipping cover art provider UrlRelationships ...
D: 09:14:09,384 /home/zas/src/picard/picard/coverart/__init__.next_in_queue:148: Skipping cover art provider CaaReleaseGroup ...
D: 09:14:09,384 /home/zas/src/picard/picard/coverart/__init__.next_in_queue:148: Skipping cover art provider Local Files ...
D: 09:14:09,386 /home/zas/.config/MusicBrainz/Picard/plugins/abbreviate_artistsort.zip/abbreviate_artistsort.abbreviate_artistsort:92: Abbreviate artist-sort: Trying to abbreviate 'Blank, Boris'.
```

* JIRA ticket (_optional_): PICARD-XXX

# Solution

Rewrite log record processing to shorten paths for main picard code.
Log records coming from Plugins are left unmodified.

- use pathlib
- get picard module real path using importlib

After:

```
D: 09:16:38,274 webservice/ratecontrol.decrement_requests:146: ('ia601602.us.archive.org', 80): Decrementing requests to: 0
D: 09:16:38,274 webservice._handle_reply:523: Received reply for http://ia601602.us.archive.org/14/items/mbid-0bb956a7-da2e-4083-861a-0dbd5e839cdf/mbid-0bb956a7-da2e-4083-861a-0dbd5e839cdf-35878421569_thumb1200.jpg: HTTP 200 (OK)  (CACHED)
D: 09:16:38,275 coverart/image.__init__:91: Saving image data 11463660cbc8ad7ac28c974a51e9e086 to '/tmp/picardyz15jmuk.jpg'
D: 09:16:38,275 coverart._set_metadata:73: Cover art image stored to metadata: CaaCoverArtImage(url='http://coverartarchive.org/release/0bb956a7-da2e-4083-861a-0dbd5e839cdf/35878421569-1200.jpg', types=['front', 'spine'], support_types=True, support_multi_types=True, is_front=False) [w=1200 h=936 mime=image/jpeg ext=.jpg datalen=281208 file=/tmp/picardyz15jmuk.jpg]
D: 09:16:38,276 coverart.next_in_queue:148: Skipping cover art provider UrlRelationships ...
D: 09:16:38,276 coverart.next_in_queue:148: Skipping cover art provider CaaReleaseGroup ...
D: 09:16:38,276 coverart.next_in_queue:148: Skipping cover art provider Local Files ...
D: 09:16:38,278 /home/zas/.config/MusicBrainz/Picard/plugins/abbreviate_artistsort.zip/abbreviate_artistsort.py.abbreviate_artistsort:92: Abbreviate artist-sort: Trying to abbreviate 'Blank, Boris'.

```

# Action

### CODE REVIEW

**Comment by zas** [comment]
@phw: can you test it with packaged binaries (on various platforms)?

**Comment by rdswift** [comment]
This looks good.  What do you think of doing something similar for logging from plugins?

**Comment by zas** [comment]
> This looks good. What do you think of doing something similar for logging from plugins?

This is intentionally different because plugins can be installed anywhere.
As you can see above the path prefix is `/home/zas/.config/MusicBrainz/Picard/plugins/abbreviate_artistsort.zip/` which isn't  under picard module at all.

BTW it was more or less the case before too (we were stripping .py only), for the same reason.
We could use the module itself though and log as [PLUGIN name] or the like; but it would hide the actual source path, and for debugging that's useful.

**Review by phw — APPROVED** [review]
This is great. Makes the log way more readable in many cases.

I tested this also on Windows and macOS and it works there as expected.

**Comment by zas** [comment]
For reference, it was fixed for pyinstaller packages by https://github.com/metabrainz/picard/pull/2234

**Pull request merged**
