### PR TITLE
PICARD-2627: Handle exceptions better in piper sender/reader threads

### PR DESCRIPTION
**Pull request by zas**
# Summary

* This is a…
  * [x] Bug fix
  * [ ] Feature addition
  * [ ] Refactoring
  * [ ] Minor / simple change (like a typo)
  * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): PICARD-XXX

# Solution

# Action

### CODE REVIEW

**Comment by phw** [comment]
@zas This patch improves the situation for me, but does not entirely fix it. I intentionally cause an exception somewhere in the code that triggers on startup.

On current master, it shows me the error dialog, then it some threading exceptions related to the pipes in some way:

```
QSocketNotifier: Can only be used with threads started with QThread
Traceback (most recent call last):
  File "/home/phw/devel/musicbrainz/picard/tagger.py", line 17, in <module>
    main(os.path.join(basedir, 'locale'), True)
  File "/home/phw/devel/musicbrainz/picard/picard/tagger.py", line 1464, in main
    tagger = Tagger(picard_args, localedir, autoupdate, pipe_handler=pipe_handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phw/devel/musicbrainz/picard/picard/tagger.py", line 334, in __init__
    load_user_collections()
  File "/home/phw/devel/musicbrainz/picard/picard/collection.py", line 147, in load_user_collections
    tagger.mb_api.get_collection_list(partial(request_finished))
  File "/home/phw/devel/musicbrainz/picard/picard/webservice/api_helpers.py", line 241, in get_collection_list
    return self.get_collection(None, handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phw/devel/musicbrainz/picard/picard/webservice/api_helpers.py", line 237, in get_collection
    return self.getx(path, handler, priority=True, important=True,
           ^^^^^^^^^
AttributeError: 'MBAPIHelper' object has no attribute 'getx'. Did you mean: 'get'?
E: 11:55:38,240 util/thread.run:69: Traceback (most recent call last):
  File "/home/phw/devel/musicbrainz/picard/picard/util/pipe.py", line 245, in read_from_pipe
    res = reader.result(timeout=timeout_secs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 458, in result
    raise TimeoutError()
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/phw/devel/musicbrainz/picard/picard/util/thread.py", line 66, in run
    result = self.func()
             ^^^^^^^^^^^
  File "/home/phw/devel/musicbrainz/picard/picard/tagger.py", line 384, in pipe_server
    messages = [x for x in self.pipe_handler.read_from_pipe() if x not in IGNORED]
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phw/devel/musicbrainz/picard/picard/util/pipe.py", line 252, in read_from_pipe
    self.send_to_pipe(self.MESSAGE_TO_IGNORE)
  File "/home/phw/devel/musicbrainz/picard/picard/util/pipe.py", line 270, in send_to_pipe
    sender = self.__thread_pool.submit(self._sender, message + self.MESSAGE_TO_IGNORE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 167, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
```

At this point the app hangs and needs to be killed.

With the patch it does not show the pipe related threading exception, but the app still hangs until hard killed:

```
QSocketNotifier: Can only be used with threads started with QThread
Traceback (most recent call last):
  File "/home/phw/devel/musicbrainz/picard/tagger.py", line 17, in <module>
    main(os.path.join(basedir, 'locale'), True)
  File "/home/phw/devel/musicbrainz/picard/picard/tagger.py", line 1464, in main
    tagger = Tagger(picard_args, localedir, autoupdate, pipe_handler=pipe_handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phw/devel/musicbrainz/picard/picard/tagger.py", line 334, in __init__
    load_user_collections()
  File "/home/phw/devel/musicbrainz/picard/picard/collection.py", line 147, in load_user_collections
    tagger.mb_api.get_collection_list(partial(request_finished))
  File "/home/phw/devel/musicbrainz/picard/picard/webservice/api_helpers.py", line 241, in get_collection_list
    return self.get_collection(None, handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phw/devel/musicbrainz/picard/picard/webservice/api_helpers.py", line 237, in get_collection
    return self.getx(path, handler, priority=True, important=True,
           ^^^^^^^^^
AttributeError: 'MBAPIHelper' object has no attribute 'getx'. Did you mean: 'get'?
```

**Comment by zas** [comment]
@phw: I noticed something, when the process is stuck due to an exception (as shown above), you don't have to `kill -9`, but just run `python tagger.py -e QUIT' in another terminal.

That shows it is stuck in waiting remote commands, and if we disable the pipe thing totally it exits as expected.

**Comment by zas** [comment]
@phw try https://github.com/metabrainz/picard/pull/2244/commits/040d6198dae3cc273fc83c50e2543e1f788bafa5

It works somehow, not it is a clean solution but I think it helps to identify the issue.

Inspired by https://stackoverflow.com/a/62731225

**Comment by zas** [comment]
Superseded by https://github.com/metabrainz/picard/pull/2247

**Pull request closed without merging**
