### PR TITLE
PICARD-908: Rearrange the layout of the action toolbar

### PR DESCRIPTION
**Pull request by samj1912**
https://tickets.metabrainz.org/browse/PICARD-908

### CODE REVIEW

**Comment by samj1912** [comment]
screenshot from 2017-01-15 23-37-27

**Comment by mineo** [comment]
I don't have any strong feelings about this, but the "Lookup CD" button shouldn't be hidden. When tagging CD rips, this is an integral part of the workflow.

**Comment by samj1912** [comment]
@mineo it isn't hidden? It's just because of my screen width. I haven't set it to hidden by default.

See https://community.metabrainz.org/t/rearrangement-customization-of-the-action-toolbar/195108/2?u=samj1912

**Comment by zas** [comment]
> @mineo it isn't hidden? It's just because of my screen width. I haven't set it to hidden by default.

I think he means it is hidden from display, depending on screen resolution, you may have to scroll right to get it.
We really need a way to reorder icons.

**Comment by samj1912** [comment]
Updated
image

**Comment by zas** [comment]
Somehow included in https://github.com/metabrainz/picard/pull/567

**Pull request closed without merging**
