### PR TITLE
Optimize PNGs

### PR DESCRIPTION
**Pull request by scop**
Running *.png through zopflipng shaves some bytes off them.

### CODE REVIEW

**Comment by phw** [comment]
Mmmh, we had a similar pull request just recently, see https://github.com/metabrainz/picard/pull/458. I can't see the actual size difference, so likely it isn't much and doesn't make a real difference (for a desktop app anyway), but thanks for the effort :) Merging

**Comment by Freso** [comment]
Considering #458, it would be nice with a before/after size - and it would also be nice with the actual parameters used. From a cursory reading, `zopflipng` is one of the tools that can do lossy compression of the PNGs, and I'm not sure we want that. I also don't know if your invocation of `zopflipng` would override files even if the resulting file size is the same as or larger than the original (I know the tools used for #458 do not do this by default).

**Comment by scop** [comment]
The size diff isn't that big indeed, ~3KiB total IIRC. Individual size changes are visible in https://github.com/metabrainz/picard/commit/8fe381dbe6745c43d21f76468ded0c85d09b7d5c.patch

What I did was to first run everything through `zopflipng -m`, then again through `zopflipng --lossy_transparent -m` which in my experience is the recipe that gives best results. And no files whose size would increase are included in this PR. Also, don't be scared of the `--lossy_transparent` option, it just loses hidden information that has no visual impact.

**Comment by scop** [comment]
Oh, and this was done with zopflipng included with zopfli version 1.0.1.

**Pull request merged**
