### PR TITLE
Fix run scripts manually

### PR DESCRIPTION
**Pull request by YohayAiTe**
# Summary

* This is a…
  * [x] Bug fix
  * [ ] Feature addition
  * [ ] Refactoring
  * [ ] Minor / simple change (like a typo)
  * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

When manually running scripts by right-clicking on a file and choosing "Run Scripts", Picard crashes. I could not find a JIRA ticket.

# Solution

Initialised the `tagger` field in the `ScriptsMenu` class.

# Action

Additional actions required:
* [ ] Update Picard [documentation](https://github.com/metabrainz/picard-docs) (please include a reference to this PR)
* [ ] Other (please specify below)

### CODE REVIEW

**Review by phw — APPROVED** [review]
Good catch, thanks for the fix.

No ticket is ok in this case as the release version is unaffected

**Comment by phw** [comment]
@zas For some reason I can't approve the CI pipeline anymore. Also had this on another PR recently. Does it work for you?

**Comment by rdswift** [comment]
> @zas For some reason I can't approve the CI pipeline anymore. Also had this on another PR recently. Does it work for you?

For some bizarre reason, I was able to approve the CI pipeline to run for this PR.

**Comment by phw** [comment]
@rdswift Thanks for running this. Not surprising, you became part of the Picard user group for fully managing the picard-docs repo, and that group has wide access to this repo, so you actually should be able to approve the CI runs. But so should I, and I don't get the necessary button anymore. Or maybe I just don't see it. It's really weird.

**Pull request merged**
