### PR TITLE
Split About text in smaller parts to prevent unneeded re-translation.

### PR DESCRIPTION
**Pull request by zas**
# Summary

* This is a…
    * [ ] Bug fix
    * [ ] Feature addition
    * [x] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

On each new year or when adding a new author, the whole About string has to be translated again.

# Solution

Move variable bits outside of it.

# Action

### CODE REVIEW

**Comment by zas** [comment]
> Looks good to me, I would only change the naming of `flaticon-credits`, this seems to be too specific. I would call it just `icon-credits` or maybe `artwork-credits`.

Actually it was intentional, those credits are specific to flaticon, if, in the future, we have to add more icons credits they are likely to be in another set.

**Comment by zas** [comment]
> I thought the credits for samj1912 do not refer to flaticons, or did I get this wrong? Otherwise I'm fine with this.

You may be right. @samj1912 ??

**Comment by samj1912** [comment]
Yeah, the ones I made are not flat icon ones.

**Comment by zas** [comment]
> Yeah, the ones I made are not flat icon ones.

Ok, i changed to `icons` to be less specific.
I'm not really happy though, i'd like us to be able to output credits to console, but the current stuff is very UI-oriented, with urls, and emails, i may rework this.
About emails, yours isn't displayed because of `<` and `>` around it, was it intentionnal ?

**Pull request merged**
