### PR TITLE
Visual feedback of coverart change in metadatabox

### PR DESCRIPTION
**Pull request by rahul-raturi**
Experimental PR. Related ticket: [Picard-258](http://tickets.musicbrainz.org/browse/PICARD-258). 
### Screenshot

screenshot from 2016-05-15 23-37-45

### CODE REVIEW

**Comment by samj1912** [comment]
Hey are you still working on this? If not I'd like to take this up :)

**Comment by zas** [comment]
> Hey are you still working on this? If not I'd like to take this up :)

Since the patch is not very big, feel free to create another PR for the same purpose, i think @rahul-raturi isn't active those days.

**Comment by rahul-raturi** [comment]
Sure, go ahead. I've been bit busy lately with university. 
You can continue on this pr (I can add collaborators, I guess), or maybe create a new pr, as @zas suggested.

**Comment by rahul-raturi** [comment]
Closing this PR as it is being continued at -> https://github.com/metabrainz/picard/pull/585

**Pull request closed without merging**
