### PR TITLE
Initial port of picard/* to Qt5

### PR DESCRIPTION
**Pull request by mwiencek**
I'd like Picard to have proper VoiceOver/accessibility support on Mac OS X (we've gotten several support@ emails from users who cannot use Picard at all). This might even be a prerequisite for submitting Picard to the app store.

This requires porting Picard to Qt5. The carbon version of Qt4 actually had some accessibility features enabled, but it was gutted from the cocoa version (only to be mentioned in a footnote somewhere).

This will break things as far as plugins/packaging are concerned, so I would recommend bumping the major version of Picard to 2.0.

I haven't ported any of the plugins, but can work on that if this is merged.

### CODE REVIEW

**Comment by Freso** [comment]
> IIRC it depended on mutagen support for python3

Mutagen has supported Python 3 for the last couple of releases, so that shouldn't be blocking this moving forwards any longer.

**Comment by mwiencek** [comment]
> I'd prefer 2 since it does not require to run all the builds every time the Picard tests need to run. But I know I won't have the time to do either of those and I am not sure whether it is worth the trouble.

I'll work on making a custom PPA for this.

**Comment by mwiencek** [comment]
Conflicts are fixed here but travis is still broken, a year later, so probably still won't be easy to fix until Picard supports python3.

**Comment by phw** [comment]
This might be a per-requisite to fix the high DPI issues reported at [PICARD-817](http://tickets.musicbrainz.org/browse/PICARD-817)

**Comment by mineo** [comment]
Hi,

as discussed on [Discourse](https://community.metabrainz.org/t/reducing-the-number-of-open-pull-requests/165542),
I'm going to close this because it has been tagged "Needs more work" and/or
"Update required" and there has been no activity in the last year. I will also
try to keep emails to a minimum and only leave this message on one pull request
per author, so if any other of your pull requests get closed and they match the
criteria, this is why. If new development happens on this pull request, please
leave a comment so we can reopen it!

**Comment by samj1912** [comment]
Hey, I'd like to continue up on this. 

@mwiencek, do plan on continuing with this or can I try and complete this? :)

**Comment by mwiencek** [comment]
Feel free to continue it. I'm not sure much needs doing besides fixing travis, conflicts, and documentation.

**Comment by samj1912** [comment]
Cool! :D will do! Freso also had plans to upgrade to Py3 along with pyqt5. Should we support py2-3 or just py3?

**Comment by mwiencek** [comment]
My earlier comment may no longer be relevant, since xenial has pyqt5 packaged for python2: http://packages.ubuntu.com/source/xenial/pyqt5

About supporting python3: If we can avoid it as part of this pull request, it's better to not combine too many large changes at once. When Picard does support it, my opinion is that it's not worth the effort to continue supporting python2, but it depends on what other contributors think.

**Comment by zas** [comment]
> About supporting python3: If we can avoid it as part of this pull request, it's better to not combine too many large changes at once. When Picard does support it, my opinion is that it's not worth the effort to continue supporting python2, but it depends on what other contributors think.

A 2.0 version of Picard supporting only Python3/qt5 isn't an issue for me.

**Pull request closed without merging**
