### PR TITLE
Check is naming script is used in a profile before deleting

### PR DESCRIPTION
**Pull request by rdswift**
# Summary

* This is a…
    * [ ] Bug fix
    * [ ] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [x] Other
* **Describe this change in 1-2 sentences**: Check is naming script is used in a profile before deleting.

# Problem

* JIRA ticket (_optional_): PICARD-XXX

There was no check, so a user could delete a file naming script that was set for use in a profile.

# Solution

Check is naming script is used in a profile before deleting.

# Action

### CODE REVIEW

**Comment by zas** [comment]
LGTM.

By the way, what happens if a script was removed from config file while still used in a profile? I mean we are supposed to handle valid changes made directly to config files

**Comment by rdswift** [comment]
> By the way, what happens if a script was removed from config file while still used in a profile? I mean we are supposed to handle valid changes made directly to config files

Currently it logs an error that the script was not found, but does not update the settings to replace it with a valid script id (or None).  Should we change the profile setting for that key back to None?  That might be the cleanest way of handling it.

**Comment by zas** [comment]
> Should we change the profile setting for that key back to None? That might be the cleanest way of handling it.

Yes, I agree..

**Comment by rdswift** [comment]
> > Should we change the profile setting for that key back to None? That might be the cleanest way of handling it.
> 
> Yes, I agree..

I actually decided to put the profile and settings cleanup in MainMenu so that any problems are corrected before being accessed anywhere else in the program.

**Review by zas — APPROVED** [review]

**Pull request merged**
