### PR TITLE
AB tests: Log debug message on extractor setup

### PR DESCRIPTION
**Pull request by phw**
# Summary

* This is a…
  * [x] Bug fix
  * [ ] Feature addition
  * [ ] Refactoring
  * [ ] Minor / simple change (like a typo)
  * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

Attempt to capture debug output for spurious test failures in AB extractor setup. See e.g. test run at https://github.com/metabrainz/picard/runs/4831702643?check_suite_focus=true

### CODE REVIEW

**Review by zas — APPROVED** [review]
Nice patch, good thing to have a `with` context to enable/disable logging in tests.

**Comment by phw** [comment]
@zas Not sure what to do about this. We probably don't want to merge 4d528f38d472620022eb278660a45e54c1d9eaf0 or 4c5e0129b28ce34ab807fe28b951c0489290bcce or both.

**Comment by phw** [comment]
I tested this a bit more: Maybe the right approach would be to set the log level in tests even lower, to INFO or WARNING .

By default pytest does not output any output to stdout or stderr caused by the tests, so the test run stays clean. But if a test fails the output of this test gets recorded. So the output of a timeout error for ab extractor looks like this if log level in tests is set to WARNING:

```
_______________________________________________________________________________ AcousticBrainzSetupTest.test_ab_setup_present _______________________________________________________________________________

self = <test.test_acousticbrainz.AcousticBrainzSetupTest testMethod=test_ab_setup_present>

    def test_ab_setup_present(self):
        settings['acousticbrainz_extractor'] = mock_extractor
        self.set_config_values(settings)
    
        # Try to setup AB
        ab_extractor = ABExtractor()
    
        # Extractor should be found
>       self.assertTrue(ab_extractor.available())
E       AssertionError: False is not true

test/test_acousticbrainz.py:63: AssertionError
------------------------------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------------------------------
E: 07:55:52,741 /home/phw/devel/musicbrainz/picard/picard/acousticbrainz/extractor.check_extractor_version:57: AcousticBrainz extractor failed with error: Command '['/home/phw/devel/musicbrainz/picard/.venv/bin/python', '/home/phw/devel/musicbrainz/picard/test/data/acousticbrainz/mock_acousticbrainz_extractor.py']' timed out after 0.001 seconds
W: 07:55:52,741 /home/phw/devel/musicbrainz/picard/picard/acousticbrainz/__init__.get:116: ABExtractor: failed to get version or sha: check_extractor_version('/home/phw/devel/musicbrainz/picard/test/data/acousticbrainz/mock_acousticbrainz_extractor.py') returned None
--------------------------------------------------------------------------------------------- Captured log call ---------------------------------------------------------------------------------------------
ERROR    /home/phw/devel/musicbrainz/picard/picard/acousticbrainz/extractor:extractor.py:57 AcousticBrainz extractor failed with error: Command '['/home/phw/devel/musicbrainz/picard/.venv/bin/python', '/home/phw/devel/musicbrainz/picard/test/data/acousticbrainz/mock_acousticbrainz_extractor.py']' timed out after 0.001 seconds
WARNING  /home/phw/devel/musicbrainz/picard/picard/acousticbrainz/__init__:__init__.py:116 ABExtractor: failed to get version or sha: check_extractor_version('/home/phw/devel/musicbrainz/picard/test/data/acousticbrainz/mock_acousticbrainz_extractor.py') returned None
```

If log level is CRITICAL instead we get:

```
_______________________________________________________________________________ AcousticBrainzSetupTest.test_ab_setup_present _______________________________________________________________________________

self = <test.test_acousticbrainz.AcousticBrainzSetupTest testMethod=test_ab_setup_present>

    def test_ab_setup_present(self):
        settings['acousticbrainz_extractor'] = mock_extractor
        self.set_config_values(settings)
    
        # Try to setup AB
        ab_extractor = ABExtractor()
    
        # Extractor should be found
>       self.assertTrue(ab_extractor.available())
E       AssertionError: False is not true

test/test_acousticbrainz.py:63: AssertionError
```

So this means to me we should set the log level to WARNING or even INFO for running tests but not set the `--capture=tee-sys` parameter when running pytest (which would cause all logging output always getting shown without context).

**Comment by phw** [comment]
I close this in favor of https://github.com/metabrainz/picard/pull/2041

**Pull request closed without merging**
