### PR TITLE
Add CODE_OF_CONDUCT.md (pointing to MusicBrainz CoC)

### PR DESCRIPTION
**Pull request by jflory7**
# Summary

Adds `CODE_OF_CONDUCT.md` to repo, following past discussion to include a code of conduct file for our project's [community profile](https://github.com/metabrainz/picard/community).

# Background

This was discussed about two weeks ago in the weekly meeting to meet more of the community profile requirements that GitHub marks. It also is helpful for our project to promote the Code of Conduct and make it visible to others contributing to our projects.

# Details

The document in this repo points to the full MusicBrainz Code of Conduct. It also tries to provide basic steps for someone to make a report or to ask for help in a situation regarding the Code of Conduct.

### CODE REVIEW

**Comment by Sophist-UK** [comment]
I am happy with this PR, however IMO the actual `Code of Conduct` needs to be updated to cover community involvement in open source code (as it currently is focused on MB edits).

**Comment by jflory7** [comment]
@Sophist-UK Two weeks ago in the weekly meeting, we discussed the MusicBrainz CoC and how it doesn't _really_ apply easily to other *Brainz projects. @Freso was aware of this and I think the plan is to eventually move to a MetaBrainz CoC instead of only the MusicBrainz one. But until that happens, the _Community members_ section does cover some basic parts of expected behavior.

**Comment by Sophist-UK** [comment]
@jflory7 Justin - Any chance you could add a link to the chat log?

**Comment by jflory7** [comment]
@Sophist-UK The logs I have are here: https://chatlogs.metabrainz.org/brainzbot/metabrainz/2017-10-16/?msg=4020066&page=3

**Comment by samj1912** [comment]
@jflory7 I am not sure how that link is relevant? It points to MB-DB/editing CoC not coding/community CoC.

**Comment by Sophist-UK** [comment]
Yes - the chat did not really discuss the shape of a coders CoC.

**Comment by jflory7** [comment]
@samj1912 @Sophist-UK That's fair. It talks briefly about basic community etiquette, but for non-MusicBrainz projects, it leaves a lot to be desired.

If preferred, I can close this and we can revisit once @Freso and others have a chance to work on a Code of Conduct for all MetaBrainz community projects.

**Comment by Sophist-UK** [comment]
@jflory7 I am happy for this to go through and for the actual CoC to play catch-up so long as someone is owning and working on it.

**Comment by samj1912** [comment]
Closing this for now.

**Comment by phw** [comment]
Now that we have https://metabrainz.org/code-of-conduct this PR should probably be updated to use this instead.

**Pull request closed without merging**
