### PR TITLE
PICARD-728: Allow setting ratings for unmatched files

### PR DESCRIPTION
**Pull request by phw**
See [PICARD-728](http://tickets.musicbrainz.org/browse/PICARD-728)

### CODE REVIEW

**Comment by zas** [comment]
I tested this PR, i find weird rating isn't preserved when set on an unmatched file then matched.
capture du 2015-05-28 15 50 53
capture du 2015-05-28 15 46 26
capture du 2015-05-28 15 47 05

**Comment by zas** [comment]
@phw : you didn't react to the screenshots i posted

**Comment by phw** [comment]
Right. Not sure really. It is something I noticed, but it is consistent with how Picard handles tags. The only difference is that unlike other tags you don't see the old vs new value displayed. In this regard it behave like embedded cover art.

What's your expected behavior?

**Comment by zas** [comment]
Well, i expected the Rating i set on the unmatched file was carried over when matched.
Basically if i set the rating on a file before linking it to a specific track, i think my rating shouldn't be replaced by the one from MB.
This needs a dirty state for the file rating, and if it is dirty and different from the one of the track, use the file one instead.

**Comment by phw** [comment]
Might make sense. I will try this, I think I have to see how it feels like when actually using it.

My main motivation for this PR was actually that I wanted to just see the rating stored in local files I loaded. Otherwise I actually expect my MB rating to overwrite my local rating.

**Pull request closed without merging**
