### PR TITLE
PICARD-848: Cannot fetch cover art from amazon link contains https scheme.

### PR DESCRIPTION
**Pull request by Barami**
Picard 1.3.2 cannot fetch cover art from amazon.
Because, picard can only fetch information from amazon without ssl.

But some releases have an amazon url with https.
This commit fix regex for amazon url parse function.

### CODE REVIEW

**Comment by zas** [comment]
@Barami : can you give MBIDs of releases having this issue ?
Your fix is not totally correct, not sure whether we need to capture the proto part and your regex can be shorter (`https?:`).
You also need to add matching tests to https://github.com/metabrainz/picard/blob/master/test/test_amazon_urls.py

**Comment by zas** [comment]
Also, if there is no ticket already existing for this issue, you need to create on at http://tickets.musicbrainz.org/browse/PICARD, we use it to generate Changelog. When done, change PR title to include a reference to the ticket `PICARD-xxx: pr title`

**Comment by Barami** [comment]
@zas I have created issue on JIRA and explained problem in there.
http://tickets.musicbrainz.org/browse/PICARD-848

**Comment by zas** [comment]
@Barami : thanks for the changes, almost ok, but you added an extra file at top directory called 'test_amazon_urls.py' by error (i don't think it was your intention).

```
md5sum test/test_amazon_urls.py test_amazon_urls.py
aad2acbbec45e79f1d43b1ece8e14ccf  test/test_amazon_urls.py
aad2acbbec45e79f1d43b1ece8e14ccf  test_amazon_urls.py
```
Please remove it  so we can merge this PR

**Comment by Barami** [comment]
@zas Thanks and sorry. It's my fault.

**Pull request merged**
