### PR TITLE
Add signal when file naming related settings are changed

### PR DESCRIPTION
**Pull request by rdswift**
# Summary

* This is a…
  * [ ] Bug fix
  * [x] Feature addition
  * [ ] Refactoring
  * [ ] Minor / simple change (like a typo)
  * [ ] Other
* **Describe this change in 1-2 sentences**:  Adds a signal when file naming related settings are changed

# Problem

File naming related settings can be changed in a number of places, and there is no consolidated way to capture whether a setting has been changed.  Something like this is required for https://github.com/metabrainz/picard/pull/2563

* JIRA ticket (_optional_): PICARD-XXX

# Solution

This PR adds a signal to the config settings class to determine when a file naming related setting has been updated.

# Action

Additional actions required:
* [ ] Update Picard [documentation](https://github.com/metabrainz/picard-docs) (please include a reference to this PR)
* [ ] Other (please specify below)

### CODE REVIEW

**Comment by rdswift** [comment]
To make this signal more "generic", we could include a function in the `SettingConfigSection` class to provide the setting names set to check for triggering the signal.  That way it could be used to signal on different settings as required for different applications.  I can make that change if you think there might be some value in having this flexibility.

**Review by phw — COMMENTED** [review]
Generally this is a good approach. But I think we should avoid adding this very specific logic to the settings module. I'd instead have the settings emit a generic signal when settings have changed and have the update logic in e.g. the metadata box handle the specifics.

We have multiple places where we could make use of this. E.g. syncing the rename andove file settings with the menu and the script editor dialog.

**Comment by rdswift** [comment]
> Generally this is a good approach. But I think we should avoid adding this very specific logic to the settings module. I'd instead have the settings emit a generic signal when settings have changed and have the update logic in e.g. the metadata box handle the specifics.

Yeah, that makes sense.  I'll modify it to emit a signal when a setting value has changed, with the signal providing the name of the setting as an argument.  If the new value for the setting is the same as the old value then the signal will not be emitted.  This should avoid the situation of emitting signals for every setting when only one setting on an option page has changed (but all settings on the page are saved).

**Review by zas — APPROVED** [review]
Good move, it looks good to me.

**Review by phw — DISMISSED** [review]
Looks good to me.

Just an idea, but no blocker: should the signal also emit the new value and old value of the setting? Not sure we have a use case for this, but it would avoid querying the settings again.

**Comment by rdswift** [comment]
> Just an idea, but no blocker: should the signal also emit the new value and old value of the setting? Not sure we have a use case for this, but it would avoid querying the settings again.

That would make it more complete for sure.  I'll have a look.

**Review by phw — APPROVED** [review]
Great, thanks.

**Review by zas — APPROVED** [review]
Even better with old & new values passed to signal, LGTM.

**Pull request merged**
