### PR TITLE
Add album column

### PR DESCRIPTION
**Pull request by evandrocoan**
# Summary

    * [ ] Bug fix
    * [ ] Feature addition
    * [ ] Refactoring
    * [x] Minor / simple change (like a typo)
    * [ ] Other

* **Describe this change in 1-2 sentences**:

Create a simple Sublime Project and add the Album column.

# Problem

Missing album column and a lot of free spacing.

* JIRA ticket: https://tickets.metabrainz.org/browse/PICARD-170

# Solution

Add Album column item.

### CODE REVIEW

**Comment by zas** [comment]
Commits 9ff5a90 and 82a7f4b are unrelated to the ticket cited.
Can you explain why and how commit 5811aed07541285ce352110f4b2d9c1e2c1ee26a fix PICARD-170 ??
Frankly, this PR makes no sense.

**Comment by evandrocoan** [comment]
> Can you explain why and how commit 5811aed fix PICARD-170 ??

Does fix, it is related to.

> Commits 9ff5a90 and 82a7f4b are unrelated to the ticket cited.
> Frankly, this PR makes no sense.

Do you prefer 3 pull requests changing 1 line of code each?

**Comment by zas** [comment]
> Does fix, it is related to.

Can you elaborate ?

> Do you prefer 3 pull requests changing 1 line of code each?

Yes, unrelated changes = different PRs.

**Comment by samj1912** [comment]
> Does fix, it is related to.
It does not actually and is completely redundant.
see https://usercontent.irccloud-cdn.com/file/wMMGO5mT/image.png
The album name is already there as the parent item of each track, this is entirely just a waste of UI space.

> Do you prefer 3 pull requests changing 1 line of code each?

I would not prefer those 2 commits at all infact. They bring nothing useful to the repo as 1. - we do not check in IDE specific files to the repo. 2. The batch file is entirely useless. Why would a person not just run the command himself or use the packaged windows version exe.

**Comment by zas** [comment]
> I would not prefer those 2 commits at all infact. They bring nothing useful to the repo as 1. - we do not check in IDE specific files to the repo. 2. The batch file is entirely useless. Why would a person not just run the command himself or use the packaged windows version exe.

I tend to agree.

**Comment by evandrocoan** [comment]
> It does not actually and is completely redundant.

I actually eat the `not`, it should be `It does not` instead of `It does`.


> The album name is already there as the parent item of each track, this is entirely just a waste of UI space.

Indeed, for the right side it shows redundant. But for the left side, there is nothing to show the album:

image

I should figure out how to not shot the `Album` column on the right side, but only on the left side. You guys seems to be mirroring them.


> we do not check in IDE specific files to the repo

Why force everybody create theirs IDE configurations from scratch?

I was looking for some QT creator project to open, but could find none. Not adding any IDE related project is everything but not useful. 


> The batch file is entirely useless.

You do not seem to develop this on windows. How I am supposed to open this program?
Without the batch file I am obeyed to go to the picard folder, open a terminal and run that command every time I would like to run my fork of picard. Your adding on PATH by setup.py is not working, not even running as administrator.


> Why would a person not just run the command himself or use the packaged windows version exe.

Because it does work building an .exe on windows: https://tickets.metabrainz.org/browse/PICARD-1173
And why build a .exe if I can run from the source? Unless I am distributing it to the others, otherwise I would not be required to build an exe.

**Comment by zas** [comment]
@evandrocoan : If we ask clarifications it is because we don't understand what you are trying to do, and we don't understand because you don't explain. Your last comment is hardly understandable, you ask questions instead of giving answers.
Sorry buddy, but that's not the way to go with MetaBrainz projects and teams.

Feel free to propose a **clean and documented patch actually addressing the ticket it is linked to**, respect feedback comments, especially when they come from maintainers of the project, explain what you are doing and why.

**Comment by evandrocoan** [comment]
> respect feedback comments

I never disrespected your comments. You need to quote which comment I say I disrespected, because I have no clue.

> If we ask clarifications it is because we don't understand what you are trying to do

Obviously, but why do you explicitly say this?

> we don't understand because you don't explain

What did you not understand from my explanation?

If you do not quote me, I will never know what passes on you mind, i.e., what you did not understood.


> Your last comment is hardly understandable

What is hard to understand? If you do not quote me, I will never know what you cannot understand.


> you ask questions instead of giving answers.

I gave you my answer and a replayed is another question. What answer I gave to you, and you only see a question and not answer? I can quote it, so I know what you are talking.


> explain what you are doing and why

1. I did add the `run_picard.bat` because without it on Windows, I cannot run picard from the source with/by creating a shortcut on my desktop.
1. I created `MusicBrainzPicard.sublime-project` because is very useful to have a project file you can right forward open.
1.  I added the line `(N_('Album'), 'album'),` because if very useful to have the album name on the left side.

Now, what did you now understand about what did I do?

**Comment by Sophist-UK** [comment]
1. If you want to create a batch file on your own PC, you are of course free to do so. But including it in the Picard repo is incorrect.

2. Not sure who it is useful to - but @samj1912 @zas and myself don't consider it useful to th ePicard project as a whole.

3. This is the core of your PR - and so the only part that should be included.

Even assuming that there is sufficient interest in having the album column to justify it being included in Picard, not everyone would want to see this. So there would need to be a Picard option to display this if the user decides they want to see it. 

Have you thought about adding this functionality using a plugin instead? Users who want this functionality can add the plugin, and the evaluation criteria for accepting new plugins are far lower than for accepting changes to the core Picard code.

**Comment by Sophist-UK** [comment]
> I added the line (N_('Album'), 'album'), because if very useful to have the album name on the left side.

P.S. As far as I can see, your code change would add the new column on the right hand side.

**Comment by Sophist-UK** [comment]
P.P.S. You have marked this as a "Minor / simple change (like a typo)" when it is clearly intended to add new functionality.

**Comment by evandrocoan** [comment]
> As far as I can see, your code change would add the new column on the right hand side.

It add it on both sides. But only the right side is redundant. As both left and right side are mirrored, I would have to change more code to only add it on the left side, however I do not care about the redundant column on the right side.

> You have marked this as a "Minor / simple change (like a typo)" when it is clearly intended to add new functionality and is therefore a "Feature addition".

Sorry, I cannot judge correctly between minor and feature with so simple changes.


> Have you thought about adding this functionality using a plugin instead?

I did not.  I created one at:

1. https://github.com/metabrainz/picard-plugins/pull/138 Add the Album column to the main window panel.

**Pull request closed without merging**
