### PR TITLE
More config path changes

### PR DESCRIPTION
**Pull request by rdswift**
# Summary

* This is a…
    * [ ] Bug fix
    * [ ] Feature addition
    * [ ] Refactoring
    * [x] Minor / simple change (like a typo)
    * [x] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): PICARD-XXX

Further potential changes as a result of the discussion in https://github.com/metabrainz/picard/pull/1903  (You guys are just way to quick to merge when you still have comments. :wink: )

# Solution

A couple of quick potential changes for consideration:

- Replace QLineEdit box with QLabel and QScrollArea.
- Remove configuration file path information from the About dialog.

The label in scroll area looks okay for short paths with no scroll bar displayed, but I'm not sure I really like it with the scroll bar.  I can also take a look at changing the style properties for the QLineEdit widget to not make it look so much like an editable field.

# Action

### CODE REVIEW

**Comment by rdswift** [comment]
Here's how they look.  Seeing them together I think I actually prefer the scroll bar option.  It seems a bit less clumsy to use if the line is long.

## Label and Scroll Area Option

### Short Line Display

image

### Long Line Display

image

## LineEdit with Label Color Scheme

### Short Line Display

image

### Long Line Display

image

**Comment by zas** [comment]
I think the line edit with color scheme works better, and code is likely simpler.

**Comment by phw** [comment]
I agree on this

**Comment by rdswift** [comment]
> I think the line edit with color scheme works better, and code is likely simpler.

Changes made to use the QLineEdit with QLabel color scheme and no scroll bar.

**Review by zas — APPROVED** [review]
LGTM

**Pull request merged**
