### PR TITLE
PICARD-1951: Prevent complete hiding of metadata box or file panes

### PR DESCRIPTION
**Pull request by phw**
# Summary
Prevent complete hiding of metadata box or file panes

* This is a…
    * [x] Bug fix
    * [ ] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other

# Problem
By completely dragging the splitter between the file panes and the metadata box up or down the user can completely hide any of those parts. This results in a UI that appears broken, and without any hint to the user that there is a missing part and that they can make it visible again.

See the screenshots in PICARD-1951

* JIRA ticket (_optional_): PICARD-1951

# Solution
Set the parts of the splitter to be not-collapsible.

Note: According to Qt5 documentation one should be able to do this with a single call to `splitter.setChildrenCollapsible(False)`, see https://doc.qt.io/qt-5/qsplitter.html#childrenCollapsible-prop

But when I tried this (with PyQt 5.15.1 on Windows 10) it had no effect. Only setting `setCollapsible` per element worked.

# Action

### CODE REVIEW

**Comment by zas** [comment]
I tested `mainLayout.setChildrenCollapsible(False)` and it works but ONLY after removing existing related persist settings (try after removing config file). So the issue is not with the function itself, but rather with persistence of previous settings for the splitter.

This is exactly what is reported on https://bugreports.qt.io/browse/QTBUG-35311 (not a bug).

Obviously it would be preferrable to use  `mainLayout.setChildrenCollapsible(False)` since it's cleaner, but not sure how to fix the persist issue.

**Comment by phw** [comment]
Now I see, thanks for investigating. What about just clearing the peristet splitter config with a config migration?

And we probably should do the same for the file pane splitter, I think this is also collapsible which results in a seemingly broken UI.

**Comment by zas** [comment]
> What about just clearing the peristet splitter config with a config migration?

Yes, it would be a solution.

**Comment by phw** [comment]
I have updated the PR to solve this more compete. I also undid setting the splitter handle in between file views and metadata box to only 1 pixel. That is a small visual change, as it makes the handle actually visible. IMHO it makes it clearer that the metadata box can be resized (which is a very useful feature). Some might say it looks better without this handle in between, but I actually think it is a very minor visual difference.

**Comment by phw** [comment]
Why does codacy complain for the two Option lines that they are not assigned, but does not care about all the other options defined the same way in that file?

**Comment by zas** [comment]
> Why does codacy complain for the two Option lines that they are not assigned, but does not care about all the other options defined the same way in that file?

Likely because of trailing commans on those lines ;)

**Comment by phw** [comment]
Missed that. Now Codacy is happy :)

**Review by zas — APPROVED** [review]

**Pull request merged**
