### PR TITLE
PICARD-2231: Build with Python 3.8 on Windows

### PR DESCRIPTION
**Pull request by phw**
# Summary

* This is a…
    * [x] Bug fix
    * [ ] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): PICARD-2231, PICARD-2230

Try to build the Windows packages with Python 3.8 again. This caused issues in PICARD-2067, but either those are now resolved or we should investigate deeper.

Not using Python 3.9, as this would drop Win 7 support. For now we can maintain Win 7 support, at least as long as there is a supported Python version and we have no other requirement forcing us to update. We still seem to have quite some users on Win 7.

# Solution

# Action

### CODE REVIEW

**Comment by phw** [comment]
Works for me, both the installer and portable build run on Windows 10. The Python version included is 3.8.10, which is exactly what we need.

@rdswift Could you check the build at https://github.com/metabrainz/picard/actions/runs/933615461 and see if this works on your Windows 7?

**Comment by rdswift** [comment]
I tried the portable version and it seems to work just fine on my Windows 7 system.  I assume that the install version should also work, so I haven't tried it.

**Comment by phw** [comment]
Thanks for testing. I merge this and we can get wider testing.

But could you test the installer anyway? I think it should work this time, but it can behave differently then the installed version in regards to startup as it uses a bit different bootstrapping code.

**Comment by rdswift** [comment]
Just tested the install version and everything seemed to work fine, other than some oddities regarding the script editor (but I don't think those have anything to do with your changes).  Well done.

**Pull request merged**
