### PR TITLE
Use requirements.txt for pip package install_requires

### PR DESCRIPTION
**Pull request by phw**
# Summary

* This is a…
    * [ ] Bug fix
    * [ ] Feature addition
    * [x] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): PICARD-XXX

- We frequently forget to update setup.py if we have changes in requirements, leading to broken builds
- We do not currently specify version restrictions in setup.py, which might cause incompatible depedencies being used by pip
- Redundancy

# Solution

Read requirements.txt and use it for install_requires

# Action
I considered putting some of the dependency into extra_requires. But this is only about discid and markdown, and I think it is preferable to have both installed. Also I think it is an unneeded complication.

### CODE REVIEW

**Comment by phw** [comment]
In 8ea9a591 I also updated the version specification. Trying to specify a version for all dependencies and using the compatible release operator to allow only minor versions. E.g. currently PyQt5>=5.10 would also include 6.0, but that would be incompatible. Now it is PyQt5~=5.10, which matches all 5.x releases >= 5.10

**Comment by Sophist-UK** [comment]
Can't you say `PyQt5>=5.10,<6`?

**Comment by phw** [comment]
> Can't you say `PyQt5>=5.10,<6`?

That's equivalent to `PyQt5~=5.10`, see https://www.python.org/dev/peps/pep-0440/#compatible-release

**Comment by Sophist-UK** [comment]
> > Can't you say `PyQt5>=5.10,<6`?
> 
> That's equivalent to `PyQt5~=5.10`, see https://www.python.org/dev/peps/pep-0440/#compatible-release

Ah - yes - so `~=` is actually better. 👍

**Review by zas — APPROVED** [review]
Lgtm

**Pull request merged**
