### PR TITLE
PICARD-792: Customized tiles for Windows 10 start menu

### PR DESCRIPTION
**Pull request by phw**
# Summary
Add layout information for Windows 10 start menu tiles

* This is a…
    * [ ] Bug fix
    * [x] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): [PICARD-792](https://tickets.metabrainz.org/browse/PICARD-792)

# Solution
Add VisualElementsManifest.xml to define the layout of the start menu tiles. Documentation on this is a bit sparse, the main documentation is for UWP (Universal Windows Platform) apps, see https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/appxmanifestschema/element-visualelements

However, tile config for normal win32 desktop apps differs. E.g. only small and medium tiles are supported and you cannot customize the name here (except chaging the start menu shortcut. I used the config of Firefox as a basis and customized it for Picard.

Here is how it looks like:

screenshot-2018-10-05-08-33-56
screenshot-2018-10-05-08-33-34

Here is how it used to look like without the customization:

screenshot-2018-10-05-08-32-16
screenshot-2018-10-05-08-31-48

# Action

### CODE REVIEW

**Comment by phw** [comment]
@rdswift @samj1912 Any comments / opinions / ideas on this?

**Comment by samj1912** [comment]
LGTM, not really a big fan of the bg color, but I guess that's another matter entirely/personal preference.

**Comment by rdswift** [comment]
Looks okay to me too.  As @samj1912 said, the background color is more of a personal preference.  My preference is more for transparent background, but that's neither here nor there.  The larger icon definitely looks better.

**Comment by phw** [comment]
While I actually like the color, I don't have any strong opinion about it. To be honest I don't even remember how I got thiscolor,  these changes have been lying around half working for two years :) 

Usually I would either have picked that from somewhere on the website or I just changed the lightness value of the HSL representation of the logo's purple.

I can try some variation of the orange as well. But in any case this is definitely much better than the default blue, which does not really harmonize with the logo's colors.

**Comment by phw** [comment]
Ok, scratch that idea of me coming up with an alternative color. In moments like this it becomes too obvious that I'm primarily a web backend developer :D

I'm going to merge this and ask on the forums for some feedback

**Pull request merged**
