### PR TITLE
PICARD-2179: Persist state of scripting docs pane

### PR DESCRIPTION
**Pull request by phw**
# Summary

* This is a…
    * [x] Bug fix
    * [ ] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): PICARD-2179

Persist the state of the scripting docs in the script editor dialog.

### CODE REVIEW

**Review by zas — APPROVED** [review]

**Review by rdswift — APPROVED** [review]
This looks good to me.

Is there any benefit in also persisting things like window size and location, similar to the Options window?  I'm okay without it, but others might find it odd that this one dialog always starts with the default size.

**Comment by phw** [comment]
Yes, I think it would be beneficial to restore this. Since this dialog derives from PicardDialog a simple

    self.restore_geometry()

in init after setupUi() should already fix this

**Comment by rdswift** [comment]
Along with a corresponding `self.save_geometry()` in the closing event.  Were you planning on adding this or did you want me to add a PR for it?

**Comment by phw** [comment]
> Along with a corresponding self.save_geometry() in the closing event. 

That's handled automatically already.

I'll add that when I merge this PR

**Comment by rdswift** [comment]
> That's handled automatically already.

I'm not so sure about that because `closeEvent()` has been redefined in `scripteditor.py`.  Perhaps the redefined close event should also be calling `super.closeEvent()` ?

**Comment by phw** [comment]
You are right, closeEvent should call super, but only if it is actually closing. This would also ensure other things on the finished signal would run. I implemented saving the window state at https://github.com/metabrainz/picard/pull/1817

**Pull request merged**
