### PR TITLE
Add .mailmap file.

### PR DESCRIPTION
**Pull request by Freso**
Consolidate some of the mismatching author and committer name:email pairs in the logs.

See https://git-scm.com/docs/git-shortlog#_mapping_authors

------

I was trying to do some code analysis on the code and the results got somewhat skewed due to mismatching of commits to disparate authors when they were in fact the same author using multiple names and/or e-mail addresses.

@lalinsky, @samj1912, @Sophist-UK, and @suhas2go are you okay with this? Do you want to be credited differently?

### CODE REVIEW

**Comment by samj1912** [comment]
Good for me

**Comment by samj1912** [comment]
You might also want to merge 
Philipp Wolfer phil@parolu.io
Philipp Wolfer ph.wolfer@gmail.com
Philipp Wolfer ph.wolfer@googlemail.com

and

**Comment by Sophist-UK** [comment]
I'm fine with this.

**Comment by Freso** [comment]
> You might also want to merge

Those are not an issue since they're already the same name (and there aren't other using the same name with a different e-mail).

**Comment by suhas2go** [comment]
Fine with me as well :)

**Comment by zas** [comment]
@samj1912 : github@ for me

**Comment by Freso** [comment]
@zas You've used the same name for all of your commits and no one else has committed anything using the same name as you, so you don't need an entry in the .mailmap file.

**Pull request merged**
