### PR TITLE
PICARD-1795: Allow deleting iTunNORM and iTunPGAP tags from ID3

### PR DESCRIPTION
**Pull request by phw**
# Summary

* This is a…
    * [x] Bug fix
    * [ ] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem
The tags `comment:iTunNORM` and `comment:iTunPGAP` in ID3 tags cannot be deleted.

* JIRA ticket (_optional_): PICARD-1795

# Solution
There was a special code preventing the deletion of those tags added in https://github.com/metabrainz/picard/commit/bff60dab8a69674bfe14e6b5f02b5b597bdcb4ec

I don't see any harm being done allowing those tags to be deleted on request. There is some special handling for storing the `iTunNORM` tag as iTunes expected it, but this is independent of the issue of allow the deletion.

# Action

### CODE REVIEW

**Comment by phw** [comment]
@samithaj Can you please take a look at this? You added the original code and I might be missing something

**Comment by samithaj** [comment]
> @samithaj Can you please take a look at this? You added the original code and I might be missing something
I think it's @samj1912

**Comment by phw** [comment]
> I think it's @samj1912

Yes of course . Sorry for bothering you, I wasn't careful with the autocompletion :(

**Comment by samj1912** [comment]
This has been a while. I don't exactly remember this, but it had something to do with the fact that iTunes needs case sensitive tags or something and mutagen id3 didn't support that. Anyway, lgtm. I can't find any resources as of right now backing up the above.

**Pull request merged**
