### PR TITLE
PICARD-1662: Do not save too large images to FLAC

### PR DESCRIPTION
**Pull request by phw**
# Summary
Save FLAC files even if images are too large to embed.

* This is a…
    * [x] Bug fix
    * [ ] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem
FLAC has a maximum block size of 16 MB. Currently trying to save FLAC files with images that are larger than this gives a saving error. It is impossible to save the files at all.

* JIRA ticket (_optional_): PICARD-1662

# Solution
Check the expected block size on save and only save images if they have a valid size. Log errors otherwise.

This is a fix for the immediate saving issue reported in PICARD-1662. This is not supposed to be a full solution. As noted in PICARD-1662 it would be preferable if Picard could detect this condition earlier and provide builtin resizing capabilities. This is tracked in PICARD-1663 and related tickets.

# Action

### CODE REVIEW

**Comment by phw** [comment]
I added a test case

**Comment by Sophist-UK** [comment]
This is a good catch, but - assuming that it is possible - it would be even better to recognise an album has a track which is a FLAC file and to download an image size which was compatible (in addition to the image size in settings.

**Comment by phw** [comment]
@sophist-uk see related tickets

**Comment by Sophist-UK** [comment]
Ah sorry - should have read the description first.

**Pull request merged**
