### PR TITLE
Avoid stderr conversion to ascii errors...

### PR DESCRIPTION
**Pull request by Sophist-UK**
... when e.g. artist name is not ascii.

### CODE REVIEW

**Comment by mineo** [comment]
I've never seen an error related to automatic conversion at that place, even with albums like https://musicbrainz.org/release/845184cc-7c55-42dd-ae20-cd1b39975871 that have characters outside of the ascii range all over the place. How do I get one of those errors?

**Comment by Sophist-UK** [comment]
I got this on windows - not sure what would happen on a mac.

Start picard from command line in order to get stderr allocated to console.
Ensure "Translate artist names to this locale" is NOT set.
Set debug mode.
Put 845184cc-7c55-42dd-ae20-cd1b39975871 into the search box and press enter.

**Comment by mineo** [comment]
I don't know how to get Picard to log to the console (cmd.exe) on windows (7). Neither 1.3.2 nor the most recent daily build log to the console in my VM.

**Comment by Sophist-UK** [comment]
Ah - you are right if you run the executable. It only logs to console when you are running from source.

**Comment by zas** [comment]
Can you show use the exact error you get ?
Is the exception UnicodeDecodeError triggered ?

**Comment by Sophist-UK** [comment]
I don't have time to recreate the error, but it is something about an ASCII character above 7F when converting to ASCII.

**Comment by mineo** [comment]
Has this also been fixed by #607 ?

**Comment by Sophist-UK** [comment]
Yes - but I wrote this so long ago I have no idea whether it is a better solution than the one we just merged.

**Comment by Sophist-UK** [comment]
Closing since #607 has been merged.

**Pull request closed without merging**
