### PR TITLE
PICARD-2848: Rename option "toolbar_multiselect" to "allow_multi_dirs_selection"

### PR DESCRIPTION
**Pull request by zas**
# Summary

* This is a…
  * [ ] Bug fix
  * [ ] Feature addition
  * [x] Refactoring
  * [ ] Minor / simple change (like a typo)
  * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

- the old name isn't explicit enough, and it isn't related to toolbar anymore at all

* JIRA ticket (_optional_): PICARD-2848

# Solution

Rename option "toolbar_multiselect" to "allow_multi_dirs_selection"

# Action

### CODE REVIEW

**Comment by zas** [comment]
Please suggest any better name for this option.

**Review by rdswift — DISMISSED** [review]
This looks good to me, and I can't think of a better name / description.

**Comment by zas** [comment]
Test is failing, I don't get why

**Review by phw — APPROVED** [review]
The old name was an odd choice indeed. Changes look good, LGTM

**Pull request merged**
