### PR TITLE
Picard 226

### PR DESCRIPTION
**Pull request by StephenWelker1024**

### CODE REVIEW

**Comment by zas** [comment]
I see 2 issues with this PR, when dropping a lot of files:
* there is no easy way to stop the clustering
* it makes UI "blink"

But having such option is nice.

**Comment by Freso** [comment]
Great to see you start tackling PICARD tickets! :smiley:

Some notes entirely unrelated to the code but more for workflow etc.:
* Please use all uppercase and include the dash when referring to tickets. Ie., "PICARD-226". This goes for PR name and commit messages and most other places.
* From my e-mail notification I had no idea what this PR was for. Please include the name of the ticket (or some other description) in the PR title, instead of just a reference to the ticket.
* Please at least include a link to the ticket in the PR's description.
* You should assign the ticket to you when you start working on it (feel free to ask on IRC if you can't figure out Jira's interface)
* Once you make the PR, you should set the status of the ticket to "in review" and add a link to the PR in a comment on the ticket.

**Comment by Freso** [comment]
Uhm. And it also seems like @opatel99 is the author of the commits… Did you @opatel99 actually write this, or have you messed up your Git authorship/user settings?

**Comment by opatel99** [comment]
@Freso I wrote this for https://github.com/metabrainz/picard/pull/448 . It seems as if @StephenWelker1024 is just starting off from where I finished, hopefully to finally vanquish this beast.

Best of luck!

**Pull request closed without merging**
