### PR TITLE
Add Github Actions status badge to README.md

### PR DESCRIPTION
**Pull request by phw**
# Summary

* This is a…
    * [ ] Bug fix
    * [ ] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [x] Other
* **Describe this change in 1-2 sentences**:

# Problem
Add a Github Actions status badge and replace the currently unused CI badges with it.

* JIRA ticket (_optional_): PICARD-XXX

# Solution

# Action

### CODE REVIEW

**Comment by phw** [comment]
@zas, @samj1912 : What do you think we should do with the existing CI configs? I am personally very happy with Github Actions. Having one place for all builds makes it much easier then the previous Travis / Appveyor mix.

Circle CI would be the only contender, but I find GHA much easier to setup. Circle CI requires you to come with a custom docker image for many use cases. So my vote would go for removing the configs for all of Appveyor, Travis and Circle.

**Comment by samj1912** [comment]
I am fine with GHA. Seems like they are faster. My only concern is that GH doesn't seem to have old versions of MacOS and as a result the latest versions of picard will have limited support. Maybe we want to keep Travis build on new releases?

**Comment by phw** [comment]
> Maybe we want to keep Travis build on new releases?

This was also my concern, but for now the build versions are compatible with macOS 10.12, which is the oldest we support anyway. Hence I'm fine with dropping Travis.

Actually the backward support for us is currently primarily dependent on the version of Qt we use. E.g. we must be careful with updating to Qt 5.14 on macOS, because they set the minimum target platform to macOS 12.13 (see https://doc.qt.io/qt-5.14/supported-platforms.html).

So in general if we do update any of Python itself, (Py)Qt or PyInstaller we must check which is the oldest macOS these builds still run with.

Things of course can change if Github updates their macOS images to newer versions. My hope would be that they provide some support for older versions and don't just upgrade immediately, but we can't tell yet. But I would worry about this once we hit the issue. It can hit us the same on any CI provider unless we control the build machine ourselves.

**Comment by zas** [comment]
I'm fine with GHA if it fulfills our goals.

**Pull request merged**
