### PR TITLE
Move PluginPriority to extension_points

### PR DESCRIPTION
**Pull request by zas**
- it is used mainly as an optional parameter by register_*() extension methods
- make it an IntEnum

# Summary

* This is a…
  * [ ] Bug fix
  * [ ] Feature addition
  * [x] Refactoring
  * [ ] Minor / simple change (like a typo)
  * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): PICARD-XXX

# Solution

# Action

Additional actions required:
* [ ] Update Picard [documentation](https://github.com/metabrainz/picard-docs) (please include a reference to this PR)
* [ ] Other (please specify below)

### CODE REVIEW

**Comment by phw** [comment]
@zas No strong opinion. It makes some sense, but it also makes sense when imported from `plugins`. `from picard.plugin import PluginPriority` seems fine to me, also from the perspective of plugins. The other question is whether this option stays as it is. So I'd probably leave this alone for now.

But anyway, if you prefer it to be moved I'm fine with that as well.

**Comment by zas** [comment]
Perhaps a better move would be to get rid of the enum and just use an integer: 0 being normal priority, positive number increased priority, negative decreased priority.

The code only use NORMAL priority, and it was meant to let one run plugins in a defined order (it can be handy in some cases). That's perhaps something that should be configurable by UI, because it really depends on the use.

**Comment by phw** [comment]
> That's perhaps something that should be configurable by UI, because it really depends on the use.

That. Organizing the order would be more helpful. And not by ordering plugins, but by ordering registered hooks.

> Perhaps a better move would be to get rid of the enum and just use an integer: 0 being normal priority, positive number increased priority, negative decreased priority.

I think the enum is helpful for the public interface (should we keep this mechanism). It makes it clear what the priority is. With 0 and 1 you get people asking what runs first.

> The code only use NORMAL priority, and it was meant to let one run plugins in a defined order (it can be handy in some cases).

Plugins also use LOW and HIGH, and there have been some constellations where this was required to be set for certain plugins to work together. But it is overall not a good mechanism and only works (more or less) if you know and control all plugins.

**Comment by zas** [comment]
I tried to drop the enum, I think it makes things simpler finally.
Let's say someone has 2 plugins, running on prio HIGH and NORMAL, and wants to run a third plugin between HIGH and NORMAL -> possible, because Python doesn't check types and one can pass a value of 50 (between 0=NORMAL and 100=HIGH), but that's hacky, and defeat the initial purpose of enum.

So I think we should just let the user passes any number, and just sort (reversed) those, not bothering with enums in this case (btw, I think that's me who added them and they were numbers before..., so I basically revert this).

See code in https://github.com/metabrainz/picard/pull/2512

**Pull request closed without merging**
